sudo: false
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install web-component-tester
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET"
  -in deploy.enc -out deploy_key -d; fi
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
  - secure: reXD4b163ciRKrT7h/UudZ9thJyKL699AFT5g6d3OWzpeljuVevF5/pKeycB332I6FYIo8dAn0pTlRSzfvx7Xnl5yQ965h+jbeT9X52+5dR8HM8W+8ek+HDaDMhXVZyu1bWiPAhLon6kXzJ19WF7ljdyOvjTQbzx4USY32boGMveOFwzsEyiIMOnmEofouqkCTy+14Ih7KsJ5HNEDhsSI/oaogZIpJETuhGkaotZakHXM4b9SOU66dT2trXz7Vo3nLJd5upzIylZ/ymek+B0+m6pyqrNeGaRCq3EyYQmxeXMA5RUgoEZPrDCZlJtWjkETT1M5er5PPChW8ut0rZvyej0UcjA0GGzGODBXJOZxSxIueRXE6aIucRi/ZOLzD32KljOQ0tXZ9u+yuxdtE2k7im91eAfCaiRV2rkDu6KhElmeSWrVQNI/vD+UgrTB8APmImMt+BUvxgUjCRPH2n2gurmpVsvhD8/qcS65ruB5nEtMburais0hiY/gHO3vVBjiHzgFkHH4Prio8NPmMBZB2/L8OmR4R57/sARhHt15FFulQhvv/+qgrsmJYjk+A8yDmJ6rp4mGy2B3hZIQRHrV3mR5FACyaBfEpq8Pm5rrhathZoUofZihKNIbcf6F51SNNKbVt0f0TpQVhw3anYnXPcmLjLQkn0MQdh5Hz5Rs3U=
  - secure: GU/ZAGLPNwJpS6CS36JucPAA/hZPMAPy2fevLHkSTHsLLJLxEW3+wUeOHggODNnwtBXqMBNyKSWFm70FEH3neUrB2uqLDpjnjJG2WVKFGCZz61f3WDl+9FZ0JPfN0Rm42DuGBzJn2PmBKFqI27ZN1FwSKJw5R81xuYpeRp65kO8sEYg9qQomZ0VV8D24ShIF1+mR759Mob6I1Jlid6U9l3MhUssI7fH23S6uXrX+sfcd9kHuL9Txx/CnRa1W1uAuorlAggBER7g9EhxDDmX27L8Mm7NKVFXrSuRs5wHAoJ/FYl6D4dZ8hXsW0fFce29e216tvNPrL3HU8GfUHrmm6QQUoPaWvecAq2AgjcTEsqZlaKwhkfGWw+8e9yT95QMbYCtMMYyLfVykZq2ANj0fbym7wIjt98bkwR0IrogXAvz3j1cAh/RCe0Wi4UiiKY3KCVX0oGHpESbjqySiYNwRpJshUUpYAZ2XihWjEWzEdrgJ00P6zUM/yugj3QgDq0b7GiBOyts/DRKBTvxlJslUMK1OCELx5v07ebNsZsye1R5622OlX3dkyRNjk6MeYRyGT1O31t3Yqf1w3Lmwtfweak38w4/+QSBCpy+EtkkoH09HwMwFEGsRlFZGXn/d4DYIDJpg0wTHYVFYky3BJUK8UHrHMiznDhoGd1ESUU7/HPE=
  - secure: Gg4QTiWEQeunQvjuYYZwhVyk+bI9XHZEEUCLISvizaVTqMdUkYkzrO/6HqSaPeFFNnZ64KyJc+BNnaQIPwa2XRMNvs2+ytMHa29LwlNN6+DTs1mgWDIQUq0Wd+NkxqbegnGAfCn/VT7dGliJVfaxW0nu3obJhT8jOWCuD2WZiZzXJZhyqqoMqVqCEUVXdNKS2FFLame/gtwKdr79RkeGKBr0HgPKi0K0DgZifO+uFDhDuP2kqAyp2Tsey7+dfuU/5fZI3dk39stl75CaQJlhAYo09rpwBx9/V5sVTwfgHJO0dYlm706rEh9gpZncSHkpdQNVSovOSKTZjOb8sip58PKhAlPvqRGnkaXvLthEF1Dq7daTIhea7IyVmzyvhNV3FGwrfmaVsapHzExIyzfuq+JBO4cf/7UIChy1g1GnP8pcfu5JFXizEE6vTpVikJguGHYvyEzvLgTUE9utQp3I3nOnwi9iTM47LgzmTWVfsP/dPy3Zh1DSgbaaDdPvu9QKAK9McP+vVqB+84j0RranPGcWO990/IrLk24EuR9f/WOEFmUZAroIqIsNgTN5HbMdcs/7CeqexrCRGurG9ZkZuwCBasPd7OBa+wCeyx/5f86CidQEvkLvsoFwvGUdq9+LYuUBTfvZpxabAiHR9htU+b58pP5dNQPSJoKFaUqYo1Q=
  - secure: IwIrsAlZ6RXtWs5f/P5cdDTMmzOhMcEty36xJUN8Plp+OT3piu9huhc9D5bDXL5N4mGwnFFaneo14ApVQNWBymyb5cEEco9r+oXBXF1ZG0etI5C3a8magiW9r7AvRZDR5YbVM2gF2lVGAHOiBEckKePG5f7zZE6thvfVliozSM2s4mwakwK5MzdZ3v49QgkEWB+Ja2Wn9SA1YcPFIwvmAbDw0EybUJt97K/LvMa3Rsm+DZ+mW46CkV2wHXKGcVAXs+2WNWpO0QScBlX3HpupXE/uWEgWS9BHHoEyhKod32A+AcCSwBXounNossRQhODAS5/HnoiPAkriWl+AC+x21wcWt/pJbKuh3ut+10sSPVkabKJk+YPv6LySfFkqyeov1dpN7ECR2GGUn6ElftGsH6mcoRBgweDyrdIcLg3uefj/zDNcEdvLRaL7Visoawa4v/kya6WIFN1qp5L35bVIW+EyAhkOgA1bsNLAEUwKL4IJqVs6t8ISRtn867yUgaJN5l1DUymwY3aE3mTZ9oCAkrrVmdeKQYv6i6x9GP0/8j+R59J309y2S2O4Y58Q4YPGaxEs7KUhLdQGLhzhb2WfdhPaongp+XlCyVRXgRNC0crsvsWzDsIyF8Nhm1pRhkARzq2ZJqQn73f/Nrc+EVqYt9EfG2dmvI8aVkOedNAc100=
