sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
    - gh-pages
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_script:
  - npm install web-component-tester
  - npm install bower
  - export PATH=$PWD/node_modules/.bin:$PATH
  - bower install
script:
- xvfb-run wct --skip-plugin sauce
- >-
  if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
env:
  global:
    - secure: arcIdBOTGxcVpD+RFhkK0OubZCVS3cloaiPBeB1pmrEx+EABVAB1FGygZfoxPFhXnu1gkmrgmg+x1CeE1h3QDbZ4oaa8/V0FhJcZRCVNeV/nII0hcc1ILz26eJZA/BnyjXez55uc8tTWZVGmJXu4SJNqF27QMoAA5R87kbOgIN/hcLKiRGS3z8mBBoFHiWmHtfLHMOOX9jMFyZwF3tt9M6cTOATEIExV7z8g14nfuOzyXud494c/sri/VRnWrzJiWpM0mYzkJCmNJ7k/tp0nJImZfSM1ZJvdVBsZQoFvgPpfn+Wk1c+pdNk4Eg2pxaf63g7QE4XARaG+OmaloPlfZHVx7USmpHXt1bGTRsM+eJaCWuTHSGY7wvVZ7jahzx9bia0E6ETD3C1NUBy32HVvTPB++SW29FpcfjG6/gEzSreT2Ji3YKA7Erpdh2WEKivSmb/zK6gZLMO7Y6ZS8M6FVErCfGC25YJ7JvoqmWGkfV61miUyoyZqkx61+f+BF5FIi+4AIwZCD/mQSiIC/y7PNjh3NsrqS/f24a/A45F1ngXOILLkQpooc9EcKUaryBf2tC21MsAwkhUE86bdc3LKEAeim2VFuER+BS6U7N6v2Ps8i9KUtLVfj+UVCPSAENMGrhoYyPX8C47lJ/M4rSnEiqZVu1mUm8OFFLDOWn7d6mE=
before_install:
  - >-
    if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k
    "$password" -in id_rsa.enc -out deploy_key -d; fi
after_success:
  - cd $TRAVIS_BUILD_DIR/scripts
  - chmod 755 ghp.sh
  - ./ghp.sh
